apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nils.gabriel.braun@gmail.com
    privateKeySecretRef:
      name: lets-encrypt
    solvers:
      - dns01:
          cloudflare:
            email: nils.gabriel.braun@gmail.com
            apiKeySecretRef:
              name: cloudflare-credentials
              key: apiKey