apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <replace-with-your-email>
    privateKeySecretRef:
      name: lets-encrypt
    solvers:
      - dns01:
          cloudflare:
            email: <replace-with-your-email>
            apiKeySecretRef:
              name: cloudflare-credentials
              key: apiKey