# permissions for end users to view containerdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: container-as-a-service
    app.kubernetes.io/managed-by: kustomize
  name: containerdeployment-viewer-role
rules:
- apiGroups:
  - apps.com.coding-monkey
  resources:
  - containerdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.com.coding-monkey
  resources:
  - containerdeployments/status
  verbs:
  - get
