apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-codingmonkey-cloud
  namespace: default
spec:
  secretName: wildcard-codingmonkey-cloud-tls
  issuerRef:
    name: lets-encrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.codingmonkey.cloud"
    - "codingmonkey.cloud"
