---
server_host_group: "servers"
server_nodes: "{{ groups[server_host_group] | sort }}"
server_bootstrap_node: "{{ server_nodes[0] }}"
server_is_bootstrap_node: "{{ inventory_hostname == server_bootstrap_node }}"

