additionalArguments:
  - '--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare'
  - '--certificatesresolvers.cloudflare.acme.email=nils.gabriel.braun@gmail.com'
  - '--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1'
logs:
  general:
    level: ERROR
ports:
  websecure:
    http3:
      enabled: false
    tls:
      enabled: true
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: cloudflare-credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: cloudflare-credentials
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"

