apiVersion: apps.com.coding-monkey/v1
kind: ContainerDeployment
metadata:
  name: weeky-demo
spec:
  image: nginx:latest
  namespace: weekly-demo
  memory: "64Mi"
  cpu: "250m"
  exposed-port: 8080
  application-port: 8080
  storage:
    size: "1Gi"
    mount-path: "/data"
    keep-after-delete: true
