apiVersion: apps.com.coding-monkey/v1
kind: ContainerDeployment
metadata:
  name: ingress
status:
    availableReplicas: 1
spec:
  image: nginx:latest
  namespace: ingress
  memory: "64Mi"
  cpu: "250m"
  port: 80
  env:
    - name: MY_ENV
      value: "my-value"
