apiVersion: v1
kind: Secret
metadata:
  namespace: weekly-demo
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 kodierter Wert von "username"
  password: cGFzc3dvcmQ=  # base64 kodierter Wert von "password"
