---
- name: Get kubeconfig
  hosts: servers
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: slurp kubeconfig file
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kube/
      run_once: true
      tags:
        - kubeconfig

    - name: Replace localhost with loadbalancer ip
      ansible.builtin.lineinfile:
        path: "./kube/{{ inventory_hostname }}/etc/rancher/k3s/k3s.yaml"
        regexp: "^\\s+server: https://127\\.0\\.0\\.1:6443"
        line: "    server: https://{{ ansible_host }}:6443"
      run_once: true
      become: false
      delegate_to: localhost
      tags:
        - kubeconfig
