apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codingmonkey-cloud
  namespace: default
spec:
  secretName: codingmonkey-cloud-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.codingmonkey.cloud"
    - "codingmonkey.cloud"
