apiVersion: apps.com.coding-monkey/v1
kind: ContainerDeployment
metadata:
  name: ingress2
spec:
  image: nginx:latest
  namespace: ingress2
  memory: "64Mi"
  cpu: "250m"
  exposed-port: 80
  application-port: 80
