apiVersion: apps.com.coding-monkey/v1
kind: ContainerDeployment
metadata:
  name: ingress3
  namespace: ingress3
spec:
  image: nginx:latest
  memory: "64Mi"
  cpu: "250m"
  replicas: 2
  port: 80
  env:
    MY_ENV: "my-value"

