---
- name: Clone kata-containers
  ansible.builtin.git:
    repo: https://github.com/kata-containers/kata-containers.git
    dest: /home/k3suser/kata-containers
    update: true
    force: true

- name: Replace false to true in kata deploy
  ansible.builtin.replace:
    path: /home/k3suser/kata-containers/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
    regexp: 'false'
    replace: 'true'

- name: Create /etc/containerd
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root

- name: Copy containerd config in /etc/containerd
  become: true
  ansible.builtin.copy:
    src: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
    dest: /etc/containerd/config.toml.tmpl
    remote_src: true
    owner: root
    group: root

- name: Apply kata-deploy rbac
  become: true
  ansible.builtin.command: 
    cmd: kubectl apply -f /home/k3suser/kata-containers/tools/packaging/kata-deploy/kata-rbac/base/kata-rbac.yaml

- name: Apply kata-deploy k3s overlay
  become: true
  ansible.builtin.command: 
    cmd: kubectl apply -k /home/k3suser/kata-containers/tools/packaging/kata-deploy/kata-deploy/overlays/k3s

- name: Apply kata-deploy
  become: true
  ansible.builtin.command: 
    cmd: kubectl apply -f /home/k3suser/kata-containers/tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml

- name: Check kata-deploy pod
  become: true
  ansible.builtin.command: 
    cmd: kubectl -n kube-system wait --timeout=10m --for=condition=Ready -l name=kata-deploy pod

- name: Link containerd config to k3s
  become: true
  ansible.builtin.command:
    cmd: ln -s /etc/containerd/config.toml.tmpl /var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl

- name: Restart k3s
  become: true
  ansible.builtin.command: 
    cmd: systemctl restart k3s
